apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.storage.postgres.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.postgres.size }}
